#!/usr/bin/zsh 

### Job Parameters 
#SBATCH --partition=c23g
#SBATCH --time=1-10:00:00         
#SBATCH --gres=gpu:2
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_AltCrossAttnOnPVTSR1Test-%A_%a.out
#SBATCH --account=thes1823

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate greenearthnet2

# python /hpcwork/nq011071/greenearthnet/train.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27AltCrossAttnOnPVTSR1.yaml --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_pvt_cross_attn

python /hpcwork/nq011071/greenearthnet/testRWTH.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27AltCrossAttnOnPVTSR1.yaml /hpcwork/nq011071/greenearthnet/experiments/trainAltCrossAttnOnPVTSR1/greenearthnet/contextformer/rwthRuns/config_seed=27AltCrossAttnOnPVTSR1/checkpoints/Epoch-epoch=58-RMSEVegetation-RMSE_Veg=0.1570.ckpt --track ood-t_chopped --pred_dir /hpcwork/nq011071/greenearthnet/experiments/predictions/altCrossAttnOnPVTSR1/ood-t_chopped --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_pvt_cross_attn

python /hpcwork/nq011071/greenearthnet/eval.py /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/predictions/altCrossAttnOnPVTSR1/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/scores/altCrossAttnOnPVTSR1/ood-t_chopped