#!/usr/bin/zsh 

### Job Parameters 
#SBATCH --partition=c23g
#SBATCH --time=1-10:00:00         
#SBATCH --gres=gpu:2
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_MambaOnPVTd_state64-%A_%a.out
#SBATCH --account=thes1823

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate mamba

python /hpcwork/nq011071/greenearthnet/train.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27MambaOnPVTd_state64.yaml --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_mamba

# python test.py /hpcwork/nq011071/greenearthnet/model_configs/contextformer/contextformer6M/seed=27CrossAttnOnPVT.yaml /hpcwork/nq011071/greenearthnet/experiments/trainCrossAttnOnPVT/greenearthnet/contextformer/rwthRuns/config_seed=27CrossAttnOnPVT/checkpoints/Epoch-epoch=44-RMSEVegetation-RMSE_Veg=0.1512.ckpt --track ood-t_chopped --pred_dir /hpcwork/nq011071/greenearthnet/experiments/predictions/crossAttnOnPVT --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_pvt_cross_attn

# python eval.py /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/predictions/crossAttnOnPVT /hpcwork/nq011071/greenearthnet/experiments/scores/crossAttnOnPVT