#!/usr/bin/zsh 

### Job Parameters 
#SBATCH --partition=c23g
#SBATCH --time=1-10:00:00         
#SBATCH --gres=gpu:2
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_CrossAttnOnPVTWeatherSR1PretrainedTrain-%A_%a.out
#SBATCH --account=thes1823

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate greenearthnet2

python /hpcwork/nq011071/greenearthnet/train.py /home/nikoskot/greenearthnet/rwthRuns/seed=27CrossAttnOnPVTWeatherSR1Pretrained.yaml --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_pvt_cross_attn

# python /hpcwork/nq011071/greenearthnet/testRWTH.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27CrossAttnOnPVTPretrained.yaml /hpcwork/nq011071/greenearthnet/experiments/trainCrossAttnOnPVTPretrained/greenearthnet/contextformer/rwthRuns/config_seed=27CrossAttnOnPVTPretrained/checkpoints/Epoch-epoch=18-RMSEVegetation-RMSE_Veg=0.1499.ckpt --track ood-t_chopped --pred_dir /hpcwork/nq011071/greenearthnet/experiments/predictions/crossAttnOnPVTPretrained --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --use_pvt_cross_attn

# python /hpcwork/nq011071/greenearthnet/eval.py /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/predictions/crossAttnOnPVTPretrained /hpcwork/nq011071/greenearthnet/experiments/scores/crossAttnOnPVTPretrained