#!/usr/bin/zsh 

### Job Parameters 
#SBATCH --partition=c23g
#SBATCH --time=1-10:00:00         
#SBATCH --gres=gpu:2
#SBATCH --cpus-per-task=16
#SBATCH --output=slurm_NoStaticNoWeatherTest-%A_%a.out
#SBATCH --account=thes1823

export CONDA_ROOT=$HOME/miniforge3
source $CONDA_ROOT/etc/profile.d/conda.sh
export PATH="$CONDA_ROOT/bin:$PATH"
conda activate mamba

# python /hpcwork/nq011071/greenearthnet/train.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27ContextFormerNoStaticNoWeather.yaml --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --data_ablation

python /hpcwork/nq011071/greenearthnet/testRWTH.py /hpcwork/nq011071/greenearthnet/rwthRuns/seed=27ContextFormerNoStaticNoWeather.yaml /hpcwork/nq011071/greenearthnet/experiments/trainNoStaticNoWeather/greenearthnet/contextformer/rwthRuns/config_seed=27ContextFormerNoStaticNoWeather/checkpoints/Epoch-epoch=27-RMSEVegetation-RMSE_Veg=0.1678.ckpt --track ood-t_chopped --pred_dir /hpcwork/nq011071/greenearthnet/experiments/predictions/noStaticNoWeather/ood-t_chopped --data_dir /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset --data_ablation

python /hpcwork/nq011071/greenearthnet/eval.py /hpcwork/nq011071/earthnetThesis/GreenearthnetDataset/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/predictions/noStaticNoWeather/ood-t_chopped /hpcwork/nq011071/greenearthnet/experiments/scores/noStaticNoWeather/ood-t_chopped